name: billing_app
description: Professional Billing & Invoice App
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  printing: ^5.11.1
  intl: ^0.18.1
  pdf: ^3.10.4
  url_launcher: ^6.3.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
